apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nanoaod-argo-
spec:
  entrypoint: nanoaod-argo
  volumes:
    - name: workdir
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
  templates:
  - name: nanoaod-argo
    script:
      image: cmsopendata/cmssw_7_6_7-slc6_amd64_gcc493
      command: [bash, /mnt/vol/commands.sh]        
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
