apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nanoaod-argo-
spec:
  entrypoint: nanoaod-argo
  volumes:
    - name: workdir
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
  templates:
  - name: nanoaod-argo
    script:
      image: cmsopendata/cmssw_7_6_7-slc6_amd64_gcc493
      command: [/bin/bash]
      source: |
        source /opt/cms/entrypoint.sh
        sudo chown $USER /mnt/vol
        git clone -b odws2022-ttbaljets-prod https://github.com/cms-opendata-analyses/PhysObjectExtractorTool.git
        cd PhysObjectExtractorTool/PhysObjectExtractor
        scram b
        cmsRun python/poet_cfg.py True 
        mv myoutput.root /mnt/vol/
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
