apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nanoaod-argo-
spec:
  entrypoint: nanoaod-argo
  volumes:
    - name: workdir
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
  templates:
  - name: nanoaod-argo
    script:
      image: cmsopendata/cmssw_5_3_32_vnc
      command: [/bin/bash]
      source: |
        #source /opt/cms/entrypoint.sh
        sudo chown $USER /mnt/vol
        echo pwd `pwd`
        git clone git://github.com/katilp/cmssw-container-workflow.git
        cd cmssw-container-workflow
        echo pwd `pwd`
        echo ls -l `ls -l`
        
        echo git versions:
        which git
        git --version
        echo openssl versions:
        which openssl 
        openssl version || echo ignore exit code
        
        echo PATH before sourcing entrypoint: $PATH
        echo LD_LIBRARY_PATH before: $LD_LIBRARY_PATH
        echo Source a script
        source entrypoint.sh

        echo Script sourced
        echo PATH after sourcing entrypoint: $PATH
        echo LD_LIBRARY_PATH after: $LD_LIBRARY_PATH
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
