name: tests
#Running tests on all branches
on: [push,pull_request]

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: My test workflow 
    steps:
      # chmod of the entrypoint script before getting to the container
      - name: Prepare
        run: |
          pwd
          ls -l
          touch onefile.txt
      # run the container with the script in the repository
      - name: Not yet in a container
        # container: 
        #   image: 'library/hello-world'
        id: container
        run: | 
          pwd
          touch anotherfile.txt
          ls -l

      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: anotherfile.txt