name: tests
#Running tests on all branches
on: [push,pull_request]

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: My test workflow 
    steps:
      # chmod of the entrypoint script before getting to the container
      - name: Prepare
        run: |
          pwd
          ls -l
          # would have expected the files to be here but they are not so let's clone
          git clone https://github.com/katilp/cmssw-container-workflow.git workdir
          cd workdir
          chmod +x myscript.sh
          chmod +x commands.sh
          touch onefile.txt
          ls -l
      # run the container with the script in the repository
      - name: Going to a container
        # container: 
        #   image: 'library/hello-world'
        id: container
        run: | 
          pwd
          cd workdir
          ls -l 
          # if old container without cd replace the original entrypoint as it did not work here (check why) and the script has all the rest
          # docker run --entrypoint /home/runner/work/cmssw-container-workflow/cmssw-container-workflow/workdir/myscript.sh -v $(pwd):$(pwd) -w $(pwd) gitlab-registry.cern.ch/clange/cmssw-docker/cmssw_4_2_8_lowpupatch1 
          docker run -v $(pwd):$(pwd) -w $(pwd) gitlab-registry.cern.ch/clange/cmssw-docker/cmssw_4_2_8_lowpupatch1 /bin/bash ./commands.sh

      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: workdir/onefile.txt