name: tests
#Running tests on all branches
on: [push,pull_request]

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: My test workflow 
    steps:
      # chmod of the entrypoint script before getting to the container
      - name: Prepare
        run: |
          pwd
          ls -l
          # would have expected the files to be here but they are not so never mind, let's clone
          git clone https://github.com/katilp/cmssw-container-workflow.git workdir
          cd workdir
          chmod +x commands.sh
          touch onefile.txt
          ls -l
      # run the container with the script in the repository
      - name: Going to a container
        id: container
        run: | 
          pwd
          ls -l 
          # full path for the script needed
          docker run -v $(pwd):$(pwd) -w /home/cmsusr gitlab-registry.cern.ch/clange/cmssw-docker/cmssw_4_2_8_lowpupatch1 /bin/bash /home/runner/work/cmssw-container-workflow/cmssw-container-workflow/workdir/commands.sh

      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: outputs/