name: tests
on:
  pull_request:
    branches:
    - master
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: Test workflow with docker run 
    steps:
      - name: Check original disk space
        run: |
          df -h
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          df -h
          mkdir outputs
      # run the container with the script in the repository
      - name: Going to a container
        id: container
        run: | 
          chmod +x commands.sh
          mkdir shared
          chmod 777 shared
          mv commands.sh shared
          docker pull gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_10_6_30-slc7_amd64_gcc700:2023-04-05-131be08c
          docker run --rm -v ${PWD}/shared:/code  gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_10_6_30-slc7_amd64_gcc700:2023-04-05-131be08c bash -c /code/commands.sh
          echo ls -l  `ls -l `
          cp shared/output/* outputs
      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: outputs/
