name: tests
on:
  pull_request:
    branches:
    - master
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: Test workflow with docker run 
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          mkdir outputs
      # run the container with the script in the repository
      - name: Going to a container
        id: container
        run: | 
          chmod +x commands.sh
          mkdir shared
          chmod 777 shared
          mv commands.sh shared
          docker run --rm -v ${PWD}/shared:/code cmsopendata/cmssw_7_6_7-slc6_amd64_gcc493 bash -c /code/commands.sh 
          echo ls -l  `ls -l `
          cp shared/output outputs
      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: outputs/
